"""Closed domain vocabularies.

These values are serialized in release artifacts. Renaming one is a schema change.
"""

from enum import StrEnum


class AnswerState(StrEnum):
    PRESENT = "PRESENT"
    EXPLICITLY_ABSENT = "EXPLICITLY_ABSENT"
    UNKNOWN = "UNKNOWN"
    NOT_RECORDED = "NOT_RECORDED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_DISPLAYED_BY_FORM_LOGIC = "NOT_DISPLAYED_BY_FORM_LOGIC"
    INVALID = "INVALID"
    VOIDED = "VOIDED"
    SUPERSEDED = "SUPERSEDED"
    DELETED = "DELETED"


class FailureReason(StrEnum):
    UNKNOWN_FORM_VERSION = "UNKNOWN_FORM_VERSION"
    UNKNOWN_MAPPING = "UNKNOWN_MAPPING"
    UNKNOWN_LOCAL_VALUE = "UNKNOWN_LOCAL_VALUE"
    INVALID_DATA_TYPE = "INVALID_DATA_TYPE"
    INVALID_UNIT = "INVALID_UNIT"
    CONDITIONAL_LOGIC_CONFLICT = "CONDITIONAL_LOGIC_CONFLICT"
    REPEATED_GROUP_CONFLICT = "REPEATED_GROUP_CONFLICT"
    CLINICAL_INCONSISTENCY = "CLINICAL_INCONSISTENCY"
    MISSING_PROVENANCE = "MISSING_PROVENANCE"
    OMOP_CONFORMANCE_FAILURE = "OMOP_CONFORMANCE_FAILURE"
    OCR_CONFIDENCE_TOO_LOW = "OCR_CONFIDENCE_TOO_LOW"
    TEXT_ASSERTION_UNCERTAIN = "TEXT_ASSERTION_UNCERTAIN"


class LifecycleStatus(StrEnum):
    DRAFT = "DRAFT"
    SIGNED = "SIGNED"
    CORRECTED = "CORRECTED"
    VOIDED = "VOIDED"
    DELETED = "DELETED"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class QualitySeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class PublicationDecision(StrEnum):
    PUBLISH = "PUBLISH"
    QUARANTINE = "QUARANTINE"
    OMIT = "OMIT"


class ExtractionMethod(StrEnum):
    STRUCTURED_FORM = "STRUCTURED_FORM"
    FHIR = "FHIR"
    CDA_RULES = "CDA_RULES"
    NATIVE_TEXT = "NATIVE_TEXT"
    OCR_RULES = "OCR_RULES"
    SPECIALIZED_NLP = "SPECIALIZED_NLP"


class OmopDomain(StrEnum):
    CONDITION = "CONDITION"
    MEASUREMENT = "MEASUREMENT"
    OBSERVATION = "OBSERVATION"
    NOTE = "NOTE"
    NOTE_NLP = "NOTE_NLP"
