/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit Events */
    get: operations["audit_events_api_v1_audit_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Batches */
    get: operations["batches_api_v1_batches_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/concepts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog Concepts */
    get: operations["catalog_concepts_api_v1_catalog_concepts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/coverage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog Coverage */
    get: operations["catalog_coverage_api_v1_catalog_coverage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/catalog/releases/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compare Catalog Releases */
    get: operations["compare_catalog_releases_api_v1_catalog_releases_compare_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Documents */
    get: operations["documents_api_v1_documents_get"];
    put?: never;
    /** Upload Document */
    post: operations["upload_document_api_v1_documents_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/establishments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Establishments */
    get: operations["establishments_api_v1_establishments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/evidence/access-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Evidence Access Url */
    post: operations["evidence_access_url_api_v1_evidence_access_url_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/fingerprints": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fingerprints */
    get: operations["fingerprints_api_v1_fingerprints_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/form-versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Form Versions */
    get: operations["form_versions_api_v1_form_versions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/form-versions/{form_version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Form Version */
    get: operations["form_version_api_v1_form_versions__form_version_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/forms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Forms */
    get: operations["forms_api_v1_forms_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["liveness_api_v1_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_api_v1_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/lineage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lineage */
    get: operations["lineage_api_v1_lineage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mapping-releases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mapping Releases */
    get: operations["mapping_releases_api_v1_mapping_releases_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mapping-releases/{release_id}/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verify Mapping Release Artifact */
    get: operations["verify_mapping_release_artifact_api_v1_mapping_releases__release_id__verify_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mappings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mappings */
    get: operations["mappings_api_v1_mappings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/mappings/{draft_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Mapping */
    post: operations["approve_mapping_api_v1_mappings__draft_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ocr": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Ocr */
    post: operations["request_ocr_api_v1_ocr_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/omop/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Omop Events */
    get: operations["omop_events_api_v1_omop_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/omop/releases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Omop Releases */
    get: operations["omop_releases_api_v1_omop_releases_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/omop/releases/{release_id}/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verify Research Release Artifact */
    get: operations["verify_research_release_artifact_api_v1_omop_releases__release_id__verify_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pipeline-runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pipeline Runs */
    get: operations["pipeline_runs_api_v1_pipeline_runs_get"];
    put?: never;
    /** Create Pipeline Run */
    post: operations["create_pipeline_run_api_v1_pipeline_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/quarantine": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Quarantine */
    get: operations["quarantine_api_v1_quarantine_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/replays": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replay */
    post: operations["replay_api_v1_replays_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Open Session */
    post: operations["open_session_api_v1_session_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current Session */
    get: operations["current_session_api_v1_session_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/session/personas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Personas */
    get: operations["list_personas_api_v1_session_personas_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/site-summaries/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Export Site Summary */
    post: operations["export_site_summary_api_v1_site_summaries_export_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/site-summaries/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Site Summary */
    post: operations["import_site_summary_api_v1_site_summaries_import_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sources */
    get: operations["sources_api_v1_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_upload_document_api_v1_documents_post */
    Body_upload_document_api_v1_documents_post: {
      /** Upload */
      upload: string;
    };
    /** CursorPage[dict[str, Any]] */
    CursorPage_dict_str__Any__: {
      /** Data */
      data: {
        [key: string]: unknown;
      }[];
      /** Next Cursor */
      next_cursor?: string | null;
      /** Total */
      total: number;
    };
    /** EvidenceAccessRequest */
    EvidenceAccessRequest: {
      /** Bucket */
      bucket: string;
      /**
       * Expires Seconds
       * @default 300
       */
      expires_seconds: number;
      /** Key */
      key: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** MappingApprovalRequest */
    MappingApprovalRequest: {
      /** Comment */
      comment: string;
    };
    /** ReplayRequest */
    ReplayRequest: {
      /** Mapping Release Id */
      mapping_release_id: string;
      /**
       * Quarantine Id
       * Format: uuid
       */
      quarantine_id: string;
    };
    /** RunRequest */
    RunRequest: {
      /** Batch Id */
      batch_id: string;
      /** Establishment Id */
      establishment_id?: string | null;
      /** Form Id */
      form_id?: string | null;
      /** Form Version */
      form_version: string;
      /** Mapping Release Id */
      mapping_release_id?: string | null;
      /** Patient Pseudonym */
      patient_pseudonym?: string | null;
      /** Response Object Key */
      response_object_key?: string | null;
      /** Source System Id */
      source_system_id?: string | null;
    };
    /** SessionRequest */
    SessionRequest: {
      /**
       * Persona
       * @enum {string}
       */
      persona: "engineer" | "steward" | "researcher" | "operator";
    };
    /** SessionResponse */
    SessionResponse: {
      /** Actor */
      actor: {
        [key: string]: string;
      };
      /** Csrf Token */
      csrf_token: string;
      /** Expires In Seconds */
      expires_in_seconds: number;
    };
    /** SignedSiteSummary */
    SignedSiteSummary: {
      bundle: components["schemas"]["SiteSummaryBundle"];
      /** Payload Checksum Sha256 */
      payload_checksum_sha256: string;
      /** Signature Base64 */
      signature_base64: string;
      /** Signing Key Id */
      signing_key_id: string;
    };
    /** SiteMetric */
    SiteMetric: {
      /** Concept Key */
      concept_key: string;
      /** Eligible Count */
      eligible_count?: number | null;
      /**
       * Period End
       * Format: date
       */
      period_end: string;
      /**
       * Period Start
       * Format: date
       */
      period_start: string;
      /** Positive Count */
      positive_count: number;
      /** Recorded Count */
      recorded_count: number;
      /**
       * Suppressed
       * @default false
       */
      suppressed: boolean;
      /** Usable Count */
      usable_count: number;
    };
    /** SiteSummaryBundle */
    SiteSummaryBundle: {
      /** Establishment Id */
      establishment_id: string;
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Mapping Release Ids */
      mapping_release_ids: string[];
      /** Metrics */
      metrics: components["schemas"]["SiteMetric"][];
      /** Minimum Cell Threshold */
      minimum_cell_threshold: number;
      /** Research Release Id */
      research_release_id: string;
      /**
       * Schema Version
       * @default 1.0
       * @constant
       */
      schema_version: "1.0";
    };
    /** UploadValidationResponse */
    UploadValidationResponse: {
      /** Accepted */
      accepted: boolean;
      /** Checksum Sha256 */
      checksum_sha256: string;
      /** Filename */
      filename: string;
      /** Media Type */
      media_type: string;
      /** Object Key */
      object_key: string;
      /** Size Bytes */
      size_bytes: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  audit_events_api_v1_audit_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_api_v1_batches_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalog_concepts_api_v1_catalog_concepts_get: {
    parameters: {
      query?: {
        query?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalog_coverage_api_v1_catalog_coverage_get: {
    parameters: {
      query?: {
        concept_key?: string;
      };
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  compare_catalog_releases_api_v1_catalog_releases_compare_get: {
    parameters: {
      query?: {
        concept_key?: string;
      };
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  documents_api_v1_documents_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_document_api_v1_documents_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "X-Synthetic-Fixture"?: boolean;
        "x-csrf-token"?: string | null;
      };
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadValidationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  establishments_api_v1_establishments_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CursorPage_dict_str__Any__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  evidence_access_url_api_v1_evidence_access_url_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "x-csrf-token"?: string | null;
      };
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EvidenceAccessRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  fingerprints_api_v1_fingerprints_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  form_versions_api_v1_form_versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  form_version_api_v1_form_versions__form_version_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        form_version_id: string;
      };
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  forms_api_v1_forms_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  liveness_api_v1_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readiness_api_v1_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  lineage_api_v1_lineage_get: {
    parameters: {
      query?: {
        root?: string;
      };
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mapping_releases_api_v1_mapping_releases_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_mapping_release_artifact_api_v1_mapping_releases__release_id__verify_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        release_id: string;
      };
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  mappings_api_v1_mappings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_mapping_api_v1_mappings__draft_id__approve_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "x-csrf-token"?: string | null;
      };
      path: {
        draft_id: string;
      };
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MappingApprovalRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_ocr_api_v1_ocr_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "x-csrf-token"?: string | null;
      };
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  omop_events_api_v1_omop_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  omop_releases_api_v1_omop_releases_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_research_release_artifact_api_v1_omop_releases__release_id__verify_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        release_id: string;
      };
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pipeline_runs_api_v1_pipeline_runs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_pipeline_run_api_v1_pipeline_runs_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "x-csrf-token"?: string | null;
      };
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  quarantine_api_v1_quarantine_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  replay_api_v1_replays_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "x-csrf-token"?: string | null;
      };
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReplayRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  open_session_api_v1_session_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  current_session_api_v1_session_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_personas_api_v1_session_personas_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          }[];
        };
      };
    };
  };
  export_site_summary_api_v1_site_summaries_export_post: {
    parameters: {
      query?: {
        establishment_id?: string;
      };
      header: {
        "Idempotency-Key": string;
        "x-csrf-token"?: string | null;
      };
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SignedSiteSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_site_summary_api_v1_site_summaries_import_post: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
        "x-csrf-token"?: string | null;
      };
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignedSiteSummary"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sources_api_v1_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        ehrfs_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          }[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
